# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/university_transport_system
spring.datasource.username=postgres
spring.datasource.password=shubham@123

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Important for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional
spring.sql.init.mode=always
spring.jackson.serialization.fail-on-empty-beans=false